// askthedm_DarkvisionBySpecies_reference.js
// Reference table for default darkvision (in feet) by species/race

var DarkvisionBySpecies = {
    'aarakocra':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'aasimar':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'autognome':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'bugbear':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'centaur':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'changeling':  {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'deep gnome':  {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'dhampir':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'dragonborn':  {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'duergar':     {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'dwarf':       {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'eladrin':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'elf':         {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'drow':        {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'fairy':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'firbolg':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'genasi':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'giff':        {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'gith':        {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'githyanki':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'githzerai':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'gnome':       {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'goblin':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'goliath':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'hadozee':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'half-elf':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'half-orc':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'halfling':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'harengon':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'hexblood':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'hobgoblin':   {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'human':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kalashtar':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kender':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kenku':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kobold':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'leonin':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'lizardfolk':  {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'loxodon':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'minotaur':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'orc':         {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'owlin':       {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'plasmoid':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'reborn':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'satyr':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'sea elf':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'shadar-kai':  {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'shifter':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'simic hybrid':{night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'tabaxi':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'thri-kreen':  {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'tiefling':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'tortle':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'triton':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'vedalken':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'verdan':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'warforged':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'yuan-ti':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5}
    // Add more as needed
};

// Export for use in other scripts
globalThis.DarkvisionBySpecies = DarkvisionBySpecies;
