// askthedm_script_dependencies.js
// Consolidated dependency script for askthedm Roll20 scripts
// Contains: ITEM_TABLES, getRandomItem, CR_ATTRIBUTE_REFERENCE, DamageToSave, DamageToVEffect, DarkvisionBySpecies

// Display load message in the Mod Output Console
on('ready', function() {
    log('========================================');
    log('askthedm_script_dependencies.js loaded (version 2.0)');
    log('Provides: ITEM_TABLES, getRandomItem, CR_ATTRIBUTE_REFERENCE, DamageToSave, DamageToVEffect, DarkvisionBySpecies');
    log('========================================');
});

// --- Magic Item Reference ---
// (from askthedm_item_reference.js)

const ITEM_TABLES = {
    Arcana: {
        Common: [
            {name: 'Oil of Etherealness', min: 39, max: 39},
            {name: 'Portable Hole', min: 40, max: 40},
            {name: 'Potion of Clairvoyance', min: 41, max: 42},
            {name: 'Potion of Diminution', min: 43, max: 44},
            {name: 'Potion of Gaseous Form', min: 45, max: 46},
            {name: 'Potion of Giant Strength (fire)', min: 47, max: 47},
            {name: 'Potion of Giant Strength (frost or stone)', min: 48, max: 49},
            {name: 'Potion of Heroism', min: 50, max: 51},
            {name: 'Potion of Invisibility', min: 52, max: 53},
            {name: 'Potion of Invulnerability', min: 54, max: 55},
            {name: 'Potion of Mind Reading', min: 56, max: 57},
            {name: 'Quaal’s Feather Token (bird, swan boat, or whip)', min: 58, max: 59},
            {name: 'Ring of Feather Falling', min: 60, max: 61},
            {name: 'Ring of Spell Storing', min: 62, max: 62},
            {name: 'Ring of X-ray Vision', min: 63, max: 63},
            {name: 'Robe of Eyes', min: 64, max: 65},
            {name: 'Rod of Rulership', min: 66, max: 66},
            {name: 'Rod of the Pact Keeper, +2', min: 67, max: 68},
            {name: 'Scroll of Protection', min: 69, max: 70},
            {name: 'Spell Scroll (level 4 or level 5 spell)', min: 71, max: 75},
            {name: 'Staff of Charming', min: 76, max: 77},
            {name: 'Staff of Swarming Insects', min: 78, max: 79},
            {name: 'Staff of Withering', min: 80, max: 81},
            {name: 'Stone of Controlling Earth Elementals', min: 82, max: 82},
            {name: 'Wand of Binding', min: 83, max: 84},
            {name: 'Wand of Fear', min: 85, max: 86},
            {name: 'Wand of Fireballs', min: 87, max: 90},
            {name: 'Wand of Lightning Bolts', min: 91, max: 94},
            {name: 'Wand of the War Mage, +2', min: 95, max: 96},
            {name: 'Wand of Wonder', min: 97, max: 98},
            {name: 'Wings of Flying', min: 99, max: 100}
        ],
        Uncommon: [
            {name: 'Amulet of Proof against Detection and Location', min: 1, max: 1},
            {name: 'Baba Yaga’s Dancing Broom', min: 2, max: 2},
            {name: 'Bag of Holding', min: 3, max: 5},
            {name: 'Bag of Tricks', min: 6, max: 7},
            {name: 'Brooch of Shielding', min: 8, max: 8},
            {name: 'Broom of Flying', min: 9, max: 9},
            {name: 'Cap of Water Breathing', min: 10, max: 10},
            {name: 'Circlet of Blasting', min: 11, max: 11},
            {name: 'Cloak of Protection', min: 12, max: 13},
            {name: 'Cloak of the Manta Ray', min: 14, max: 14},
            {name: 'Decanter of Endless Water', min: 15, max: 15},
            {name: 'Deck of Illusions', min: 16, max: 16},
            {name: 'Driftglobe', min: 17, max: 18},
            {name: 'Dust of Disappearance', min: 19, max: 20},
            {name: 'Dust of Dryness', min: 21, max: 21},
            {name: 'Dust of Sneezing and Choking', min: 22, max: 22},
            {name: 'Elemental Gem', min: 23, max: 24},
            {name: 'Enspelled Staff (cantrip or level 1 spell)', min: 25, max: 25},
            {name: 'Eversmoking Bottle', min: 26, max: 26},
            {name: 'Eyes of Charming', min: 27, max: 27},
            {name: 'Eyes of Minute Seeing', min: 28, max: 28},
            {name: 'Figurine of Wondrous Power (silver raven)', min: 29, max: 30},
            {name: 'Gem of Brightness', min: 31, max: 31},
            {name: 'Hag Eye', min: 32, max: 32},
            {name: 'Hat of Disguise', min: 33, max: 33},
            {name: 'Headband of Intellect', min: 34, max: 34},
            {name: 'Helm of Comprehending Languages', min: 35, max: 35},
            {name: 'Helm of Telepathy', min: 36, max: 36},
            {name: 'Immovable Rod', min: 37, max: 37},
            {name: 'Lantern of Revealing', min: 38, max: 38},
            {name: 'Medallion of Thoughts', min: 39, max: 39},
            {name: 'Mithral Armor', min: 40, max: 40},
            {name: 'Necklace of Adaptation', min: 41, max: 42},
            {name: 'Oil of Slipperiness', min: 43, max: 43},
            {name: 'Pearl of Power', min: 44, max: 44},
            {name: 'Periapt of Health', min: 45, max: 45},
            {name: 'Philter of Love', min: 46, max: 47},
            {name: 'Potion of Animal Friendship', min: 48, max: 49},
            {name: 'Potion of Fire Breath', min: 50, max: 51},
            {name: 'Potion of Giant Strength (hill)', min: 52, max: 53},
            {name: 'Potion of Growth', min: 54, max: 55},
            {name: 'Potion of Poison', min: 56, max: 57},
            {name: 'Potion of Resistance', min: 58, max: 59},
            {name: 'Potion of Water Breathing', min: 60, max: 61},
            {name: 'Quaal’s Feather Token (anchor, fan, or tree)', min: 62, max: 62},
            {name: 'Ring of Mind Shielding', min: 63, max: 63},
            {name: 'Robe of Useful Items', min: 64, max: 65},
            {name: 'Rod of the Pact Keeper, +1', min: 66, max: 67},
            {name: 'Rope of Climbing', min: 68, max: 69},
            {name: 'Saddle of the Cavalier', min: 70, max: 70},
            {name: 'Sending Stones', min: 71, max: 72},
            {name: 'Slippers of Spider Climbing', min: 73, max: 74},
            {name: 'Spell Scroll (level 2 or level 3 spell)', min: 75, max: 82},
            {name: 'Staff of the Adder', min: 83, max: 83},
            {name: 'Staff of the Python', min: 84, max: 84},
            {name: 'Wand of Magic Detection', min: 85, max: 88},
            {name: 'Wand of Magic Missiles', min: 89, max: 91},
            {name: 'Wand of Secrets', min: 92, max: 93},
            {name: 'Wand of the War Mage, +1', min: 94, max: 95},
            {name: 'Wand of Web', min: 96, max: 97},
            {name: 'Wind Fan', min: 98, max: 99},
            {name: 'Winged Boots', min: 100, max: 100}
        ],
        Rare: [
            {name: 'Bag of Beans', min: 1, max: 1},
            {name: 'Bead of Force', min: 2, max: 3},
            {name: 'Bowl of Commanding Water Elementals', min: 4, max: 4},
            {name: 'Bracers of Defense', min: 5, max: 6},
            {name: 'Brazier of Commanding Fire Elementals', min: 7, max: 7},
            {name: 'Cape of the Mountebank', min: 8, max: 9},
            {name: 'Censer of Controlling Air Elementals', min: 10, max: 10},
            {name: 'Chime of Opening', min: 11, max: 12},
            {name: 'Cloak of Displacement', min: 13, max: 14},
            {name: 'Cloak of the Bat', min: 15, max: 16},
            {name: 'Cube of Force', min: 17, max: 17},
            {name: 'Cube of Summoning', min: 18, max: 18},
            {name: 'Daern’s Instant Fortress', min: 19, max: 19},
            {name: 'Enspelled Staff (level 2 or level 3 spell)', min: 20, max: 21},
            {name: 'Figurine of Wondrous Power (bronze griffon, ebony fly, golden lions, ivory goats, marble elephant, onyx dog, or serpentine owl)', min: 22, max: 23},
            {name: 'Folding Boat', min: 24, max: 25},
            {name: 'Gem of Seeing', min: 26, max: 27},
            {name: 'Helm of Teleportation', min: 28, max: 28},
            {name: 'Heward’s Handy Haversack', min: 29, max: 30},
            {name: 'Horseshoes of Speed', min: 31, max: 32},
            {name: 'Ioun Stone (reserve)', min: 33, max: 34},
            {name: 'Iron Bands of Bilarro', min: 35, max: 35},
            {name: 'Mantle of Spell Resistance', min: 36, max: 36},
            {name: 'Necklace of Fireballs', min: 37, max: 38},
            {name: 'Oil of Etherealness', min: 39, max: 39},
            {name: 'Portable Hole', min: 40, max: 40},
            {name: 'Potion of Clairvoyance', min: 41, max: 42},
            {name: 'Potion of Diminution', min: 43, max: 44},
            {name: 'Potion of Gaseous Form', min: 45, max: 46},
            {name: 'Potion of Giant Strength (fire)', min: 47, max: 47},
            {name: 'Potion of Giant Strength (frost or stone)', min: 48, max: 49},
            {name: 'Potion of Heroism', min: 50, max: 51},
            {name: 'Potion of Invisibility', min: 52, max: 53},
            {name: 'Potion of Invulnerability', min: 54, max: 55},
            {name: 'Potion of Mind Reading', min: 56, max: 57},
            {name: 'Quaal’s Feather Token (bird, swan boat, or whip)', min: 58, max: 59},
            {name: 'Ring of Feather Falling', min: 60, max: 61},
            {name: 'Ring of Spell Storing', min: 62, max: 62},
            {name: 'Ring of X-ray Vision', min: 63, max: 63},
            {name: 'Robe of Eyes', min: 64, max: 65},
            {name: 'Rod of Rulership', min: 66, max: 66},
            {name: 'Rod of the Pact Keeper, +2', min: 67, max: 68},
            {name: 'Scroll of Protection', min: 69, max: 70},
            {name: 'Spell Scroll (level 4 or level 5 spell)', min: 71, max: 75},
            {name: 'Staff of Charming', min: 76, max: 77},
            {name: 'Staff of Swarming Insects', min: 78, max: 79},
            {name: 'Staff of Withering', min: 80, max: 81},
            {name: 'Stone of Controlling Earth Elementals', min: 82, max: 82},
            {name: 'Wand of Binding', min: 83, max: 84},
            {name: 'Wand of Fear', min: 85, max: 86},
            {name: 'Wand of Fireballs', min: 87, max: 90},
            {name: 'Wand of Lightning Bolts', min: 91, max: 94},
            {name: 'Wand of the War Mage, +2', min: 95, max: 96},
            {name: 'Wand of Wonder', min: 97, max: 98},
            {name: 'Wings of Flying', min: 99, max: 100}
        ],
        'Very Rare': [
            {name: 'Amulet of the Planes', min: 1, max: 2},
            {name: 'Bag of Devouring', min: 3, max: 4},
            {name: 'Carpet of Flying', min: 5, max: 6},
            {name: 'Cauldron of Rebirth', min: 7, max: 8},
            {name: 'Cloak of Arachnida', min: 9, max: 10},
            {name: 'Crystal Ball', min: 11, max: 12},
            {name: 'Dancing Sword', min: 13, max: 13},
            {name: 'Efreeti Bottle', min: 14, max: 14},
            {name: 'Enspelled Staff (level 4 or level 5 spell)', min: 15, max: 16},
            {name: 'Figurine of Wondrous Power (obsidian steed)', min: 17, max: 18},
            {name: 'Hat of Many Spells', min: 19, max: 20},
            {name: 'Helm of Brilliance', min: 21, max: 22},
            {name: 'Horseshoes of a Zephyr', min: 23, max: 24},
            {name: 'Ioun Stone (absorption, fortitude, intellect, or leadership)', min: 25, max: 26},
            {name: 'Manual of Golems (clay, flesh, iron, or stone)', min: 27, max: 28},
            {name: 'Mirror of Life Trapping', min: 29, max: 29},
            {name: 'Nolzur’s Marvelous Pigments', min: 30, max: 31},
            {name: 'Oil of Sharpness', min: 32, max: 34},
            {name: 'Potion of Flying', min: 35, max: 38},
            {name: 'Potion of Giant Strength (cloud)', min: 39, max: 42},
            {name: 'Potion of Greater Invisibility', min: 43, max: 46},
            {name: 'Potion of Longevity', min: 47, max: 49},
            {name: 'Potion of Speed', min: 50, max: 53},
            {name: 'Potion of Vitality', min: 54, max: 57},
            {name: 'Ring of Regeneration', min: 58, max: 59},
            {name: 'Ring of Shooting Stars', min: 60, max: 61},
            {name: 'Ring of Telekinesis', min: 62, max: 63},
            {name: 'Robe of Scintillating Colors', min: 64, max: 65},
            {name: 'Robe of Stars', min: 66, max: 67},
            {name: 'Rod of Absorption', min: 68, max: 69},
            {name: 'Rod of Security', min: 70, max: 71},
            {name: 'Rod of the Pact Keeper, +3', min: 72, max: 73},
            {name: 'Spell Scroll (level 6, level 7, or level 8 spell)', min: 74, max: 85},
            {name: 'Staff of Fire', min: 86, max: 87},
            {name: 'Staff of Frost', min: 88, max: 89},
            {name: 'Staff of Power', min: 90, max: 90},
            {name: 'Staff of Thunder and Lightning', min: 91, max: 92},
            {name: 'Tome of Clear Thought', min: 93, max: 94},
            {name: 'Wand of Polymorph', min: 95, max: 97},
            {name: 'Wand of the War Mage, +3', min: 98, max: 100}
        ],
        Legendary: [
            {name: 'Apparatus of Kwalish', min: 1, max: 4},
            {name: 'Cloak of Invisibility', min: 5, max: 8},
            {name: 'Crystal Ball of Mind Reading', min: 9, max: 12},
            {name: 'Crystal Ball of Telepathy', min: 13, max: 16},
            {name: 'Crystal Ball of True Seeing', min: 17, max: 20},
            {name: 'Cubic Gate', min: 21, max: 22},
            {name: 'Deck of Many Things', min: 23, max: 23},
            {name: 'Enspelled Staff (level 6, level 7, or level 8 spell)', min: 24, max: 27},
            {name: 'Ioun Stone (greater absorption, mastery, or regeneration)', min: 28, max: 31},
            {name: 'Iron Flask', min: 32, max: 33},
            {name: 'Potion of Giant Strength (storm)', min: 34, max: 41},
            {name: 'Ring of Djinni Summoning', min: 42, max: 45},
            {name: 'Ring of Elemental Command (air, earth, fire, or water)', min: 46, max: 49},
            {name: 'Ring of Invisibility', min: 50, max: 53},
            {name: 'Ring of Spell Turning', min: 54, max: 57},
            {name: 'Ring of Three Wishes', min: 58, max: 58},
            {name: 'Robe of the Archmagi', min: 59, max: 59},
            {name: 'Scroll of Titan Summoning', min: 60, max: 61},
            {name: 'Sovereign Glue', min: 62, max: 65},
            {name: 'Spell Scroll (level 9 spell)', min: 66, max: 83},
            {name: 'Sphere of Annihilation', min: 84, max: 84},
            {name: 'Staff of the Magi', min: 85, max: 85},
            {name: 'Talisman of the Sphere', min: 86, max: 88},
            {name: 'Tome of the Stilled Tongue', min: 89, max: 92},
            {name: 'Universal Solvent', min: 93, max: 96},
            {name: 'Well of Many Worlds', min: 97, max: 100}
        ]
    },
    Implement: {
        Common: [
            {name: 'Bead of Nourishment', min: 1, max: 2},
            {name: 'Bead of Refreshment', min: 3, max: 4},
            {name: 'Boots of False Tracks', min: 5, max: 6},
            {name: 'Candle of the Deep', min: 7, max: 8},
            {name: 'Charlatan’s Die', min: 9, max: 10},
            {name: 'Cloak of Many Fashions', min: 11, max: 13},
            {name: 'Clockwork Amulet', min: 14, max: 15},
            {name: 'Ear Horn of Hearing', min: 16, max: 17},
            {name: 'Ersatz Eye', min: 18, max: 19},
            {name: 'Heward’s Handy Spice Pouch', min: 20, max: 21},
            {name: 'Horn of Silent Alarm', min: 22, max: 23},
            {name: 'Instrument of Illusions', min: 24, max: 25},
            {name: 'Instrument of Scribing', min: 26, max: 27},
            {name: 'Lock of Trickery', min: 28, max: 29},
            {name: 'Moon-Touched Sword', min: 30, max: 32},
            {name: 'Mystery Key', min: 33, max: 34},
            {name: 'Orb of Direction', min: 35, max: 36},
            {name: 'Orb of Time', min: 37, max: 38},
            {name: 'Perfume of Bewitching', min: 39, max: 40},
            {name: 'Pipe of Smoke Monsters', min: 41, max: 42},
            {name: 'Pole of Angling', min: 43, max: 44},
            {name: 'Pole of Collapsing', min: 45, max: 46},
            {name: 'Potion of Climbing', min: 47, max: 52},
            {name: 'Potion of Comprehension', min: 53, max: 58},
            {name: 'Potion of Healing', min: 59, max: 74},
            {name: 'Prosthetic Limb', min: 75, max: 76},
            {name: 'Rope of Mending', min: 77, max: 78},
            {name: 'Staff of Birdcalls', min: 79, max: 80},
            {name: 'Sylvan Talon', min: 81, max: 82},
            {name: 'Talking Doll', min: 83, max: 84},
            {name: 'Tankard of Sobriety', min: 85, max: 86},
            {name: 'Veteran’s Cane', min: 87, max: 90},
            {name: 'Walloping Ammunition', min: 91, max: 93},
            {name: 'Wand of Conducting', min: 94, max: 96},
            {name: 'Wand of Pyrotechnics', min: 97, max: 100}
        ],
        Uncommon: [
            {name: 'Alchemy Jug', min: 1, max: 2},
            {name: 'Ammunition, +1', min: 3, max: 6},
            {name: 'Bag of Holding', min: 7, max: 10},
            {name: 'Boots of Elvenkind', min: 11, max: 12},
            {name: 'Boots of Striding and Springing', min: 13, max: 14},
            {name: 'Boots of the Winterlands', min: 15, max: 16},
            {name: 'Broom of Flying', min: 17, max: 18},
            {name: 'Cap of Water Breathing', min: 19, max: 20},
            {name: 'Cloak of Elvenkind', min: 21, max: 22},
            {name: 'Cloak of Protection', min: 23, max: 24},
            {name: 'Cloak of the Manta Ray', min: 25, max: 26},
            {name: 'Decanter of Endless Water', min: 27, max: 27},
            {name: 'Driftglobe', min: 28, max: 30},
            {name: 'Dust of Disappearance', min: 31, max: 32},
            {name: 'Dust of Dryness', min: 33, max: 34},
            {name: 'Dust of Sneezing and Choking', min: 35, max: 36},
            {name: 'Enspelled Weapon (cantrip or level 1 spell)', min: 37, max: 38},
            {name: 'Eyes of Minute Seeing', min: 39, max: 40},
            {name: 'Eyes of the Eagle', min: 41, max: 42},
            {name: 'Gloves of Missile Snaring', min: 43, max: 44},
            {name: 'Gloves of Swimming and Climbing', min: 45, max: 46},
            {name: 'Gloves of Thievery', min: 47, max: 48},
            {name: 'Goggles of Night', min: 49, max: 50},
            {name: 'Hag Eye', min: 51, max: 51},
            {name: 'Helm of Comprehending Languages', min: 52, max: 54},
            {name: 'Immovable Rod', min: 55, max: 55},
            {name: 'Instrument of the Bards (Doss lute, Fochlucan bandore, or Mac-Fuirmidh cittern)', min: 56, max: 57},
            {name: 'Lantern of Revealing', min: 58, max: 59},
            {name: 'Nature’s Mantle', min: 60, max: 61},
            {name: 'Oil of Slipperiness', min: 62, max: 63},
            {name: 'Pipes of Haunting', min: 64, max: 65},
            {name: 'Pipes of the Sewers', min: 66, max: 67},
            {name: 'Potion of Growth', min: 68, max: 71},
            {name: 'Potion of Healing (greater)', min: 72, max: 80},
            {name: 'Potion of Water Breathing', min: 81, max: 84},
            {name: 'Quaal’s Feather Token (anchor, fan, or tree)', min: 85, max: 86},
            {name: 'Ring of Jumping', min: 87, max: 88},
            {name: 'Ring of Swimming', min: 89, max: 90},
            {name: 'Ring of Warmth', min: 91, max: 92},
            {name: 'Robe of Useful Items', min: 93, max: 94},
            {name: 'Rope of Climbing', min: 95, max: 96},
            {name: 'Stone of Good Luck', min: 97, max: 98},
            {name: 'Wand of Secrets', min: 99, max: 100}
        ],
        Rare: [
            {name: 'Ammunition, +2', min: 1, max: 4},
            {name: 'Bag of Beans', min: 5, max: 8},
            {name: 'Belt of Dwarvenkind', min: 9, max: 12},
            {name: 'Boots of Levitation', min: 13, max: 16},
            {name: 'Boots of Speed', min: 17, max: 20},
            {name: 'Chime of Opening', min: 21, max: 24},
            {name: 'Dimensional Shackles', min: 25, max: 28},
            {name: 'Enspelled Weapon (level 2 or 3 spell)', min: 29, max: 32},
            {name: 'Folding Boat', min: 33, max: 36},
            {name: 'Glamoured Studded Leather', min: 37, max: 40},
            {name: 'Heward’s Handy Haversack', min: 41, max: 44},
            {name: 'Horseshoes of Speed', min: 45, max: 48},
            {name: 'Instrument of the Bards (Canaith mandolin or Cli lyre)', min: 49, max: 52},
            {name: 'Ioun Stone (awareness)', min: 53, max: 56},
            {name: 'Portable Hole', min: 57, max: 60},
            {name: 'Potion of Diminution', min: 61, max: 64},
            {name: 'Potion of Gaseous Form', min: 65, max: 68},
            {name: 'Potion of Healing (superior)', min: 69, max: 76},
            {name: 'Quaal’s Feather Token (bird, swan boat, or whip)', min: 77, max: 80},
            {name: 'Ring of Evasion', min: 81, max: 84},
            {name: 'Ring of Free Action', min: 85, max: 88},
            {name: 'Rope of Entanglement', min: 89, max: 92},
            {name: 'Staff of Healing', min: 93, max: 96},
            {name: 'Wand of Enemy Detection', min: 97, max: 100}
        ],
        'Very Rare': [
            {name: 'Ammunition, +3', min: 1, max: 7},
            {name: 'Bag of Devouring', min: 8, max: 14},
            {name: 'Carpet of Flying', min: 15, max: 21},
            {name: 'Enspelled Weapon (level 4 or 5 spell)', min: 22, max: 28},
            {name: 'Horseshoes of a Zephyr', min: 29, max: 35},
            {name: 'Instrument of the Bards (Anstruth harp)', min: 36, max: 42},
            {name: 'Ioun Stone (agility)', min: 43, max: 49},
            {name: 'Lute of Thunderous Thumping', min: 50, max: 56},
            {name: 'Manual of Quickness of Action', min: 57, max: 63},
            {name: 'Nolzur’s Marvelous Pigments', min: 64, max: 70},
            {name: 'Potion of Flying', min: 71, max: 77},
            {name: 'Potion of Healing (supreme)', min: 78, max: 86},
            {name: 'Potion of Speed', min: 87, max: 93},
            {name: 'Tome of Leadership and Influence', min: 94, max: 100}
        ],
        Legendary: [
            {name: 'Enspelled Weapon (level 6, 7, or 8 spell)', min: 1, max: 17},
            {name: 'Instrument of the Bards (Ollamh harp)', min: 18, max: 34},
            {name: 'Sovereign Glue', min: 35, max: 54},
            {name: 'Sphere of Annihilation', min: 55, max: 70},
            {name: 'Talisman of the Sphere', min: 71, max: 83},
            {name: 'Universal Solvent', min: 84, max: 100}
        ]
    },
    Relic: {
        Common: [
            {name: 'Ear Horn of Hearing', min: 1, max: 8},
            {name: 'Potion of Healing', min: 9, max: 28},
            {name: 'Pot of Awakening', min: 29, max: 36},
            {name: 'Ruby of the War Mage', min: 37, max: 44},
            {name: 'Shield of Expression', min: 45, max: 52},
            {name: 'Smoldering Armor', min: 53, max: 60},
            {name: 'Spell Scroll (cantrip or level 1 spell)', min: 61, max: 80},
            {name: 'Staff of Adornment', min: 81, max: 90},
            {name: 'Staff of Flowers', min: 91, max: 100}
        ],
        Uncommon: [
            {name: 'Enspelled Staff (cantrip or level 1 spell)', min: 1, max: 5},
            {name: 'Keoghtom’s Ointment', min: 6, max: 10},
            {name: 'Mariner’s Armor', min: 11, max: 15},
            {name: 'Nature’s Mantle', min: 16, max: 20},
            {name: 'Pearl of Power', min: 21, max: 25},
            {name: 'Periapt of Health', min: 26, max: 30},
            {name: 'Periapt of Wound Closure', min: 31, max: 35},
            {name: 'Potion of Animal Friendship', min: 36, max: 40},
            {name: 'Potion of Healing (greater)', min: 41, max: 55},
            {name: 'Potion of Resistance', min: 56, max: 60},
            {name: 'Ring of Water Walking', min: 61, max: 65},
            {name: 'Sending Stones', min: 66, max: 70},
            {name: 'Spell Scroll (level 2 or level 3 spell)', min: 71, max: 80},
            {name: 'Staff of the Adder', min: 81, max: 85},
            {name: 'Staff of the Python', min: 86, max: 90},
            {name: 'Wand of Magic Detection', min: 91, max: 95},
            {name: 'Wand of the War Mage, +1', min: 96, max: 100}
        ],
        Rare: [
            {name: 'Amulet of Health', min: 1, max: 3},
            {name: 'Armor, +1', min: 4, max: 7},
            {name: 'Bowl of Commanding Water Elementals', min: 8, max: 9},
            {name: 'Brazier of Commanding Fire Elementals', min: 10, max: 11},
            {name: 'Censer of Controlling Air Elementals', min: 12, max: 13},
            {name: 'Elixir of Health', min: 14, max: 16},
            {name: 'Enspelled Staff (level 2 or level 3 spell)', min: 17, max: 19},
            {name: 'Horn of Blasting', min: 20, max: 22},
            {name: 'Horn of Valhalla (brass or silver)', min: 23, max: 25},
            {name: 'Ioun Stone (reserve or sustenance)', min: 26, max: 28},
            {name: 'Mace of Disruption', min: 29, max: 31},
            {name: 'Mace of Smiting', min: 32, max: 34},
            {name: 'Mace of Terror', min: 35, max: 37},
            {name: 'Necklace of Prayer Beads', min: 38, max: 40},
            {name: 'Periapt of Proof against Poison', min: 41, max: 43},
            {name: 'Potion of Healing (superior)', min: 44, max: 51},
            {name: 'Ring of Animal Influence', min: 52, max: 54},
            {name: 'Ring of Resistance', min: 55, max: 58},
            {name: 'Ring of Spell Storing', min: 59, max: 61},
            {name: 'Scroll of Protection', min: 62, max: 65},
            {name: 'Spell Scroll (level 4 or level 5 spell)', min: 66, max: 73},
            {name: 'Staff of Charming', min: 74, max: 76},
            {name: 'Staff of Healing', min: 77, max: 79},
            {name: 'Staff of Swarming Insects', min: 80, max: 82},
            {name: 'Staff of the Woodlands', min: 83, max: 85},
            {name: 'Staff of Withering', min: 86, max: 88},
            {name: 'Stone of Controlling Earth Elementals', min: 89, max: 90},
            {name: 'Tentacle Rod', min: 91, max: 93},
            {name: 'Wand of Paralysis', min: 94, max: 96},
            {name: 'Wand of the War Mage, +2', min: 97, max: 100}
        ],
        'Very Rare': [
            {name: 'Armor, +2', min: 1, max: 5},
            {name: 'Candle of Invocation', min: 6, max: 10},
            {name: 'Cauldron of Rebirth', min: 11, max: 15},
            {name: 'Enspelled Staff (level 4 or level 5 spell)', min: 16, max: 20},
            {name: 'Horn of Valhalla (bronze)', min: 21, max: 25},
            {name: 'Ioun Stone (insight)', min: 26, max: 30},
            {name: 'Manual of Bodily Health', min: 31, max: 35},
            {name: 'Potion of Healing (supreme)', min: 36, max: 43},
            {name: 'Potion of Vitality', min: 44, max: 50},
            {name: 'Rod of Alertness', min: 51, max: 55},
            {name: 'Spell Scroll (level 6, level 7, or level 8 spell)', min: 56, max: 65},
            {name: 'Spirit Board', min: 66, max: 70},
            {name: 'Staff of Fire', min: 71, max: 75},
            {name: 'Staff of Frost', min: 76, max: 80},
            {name: 'Staff of Striking', min: 81, max: 85},
            {name: 'Staff of Thunder and Lightning', min: 86, max: 90},
            {name: 'Tome of Understanding', min: 91, max: 95},
            {name: 'Wand of the War Mage, +3', min: 96, max: 100}
        ],
        Legendary: [
            {name: 'Armor of Invulnerability', min: 1, max: 8},
            {name: 'Armor, +3', min: 9, max: 18},
            {name: 'Enspelled Staff (level 6, level 7, or level 8 spell)', min: 19, max: 27},
            {name: 'Holy Avenger', min: 28, max: 36},
            {name: 'Horn of Valhalla (iron)', min: 37, max: 45},
            {name: 'Rod of Resurrection', min: 46, max: 54},
            {name: 'Scarab of Protection', min: 55, max: 63},
            {name: 'Scroll of Titan Summoning', min: 64, max: 72},
            {name: 'Spell Scroll (level 9 spell)', min: 73, max: 80},
            {name: 'Talisman of Pure Good', min: 81, max: 90},
            {name: 'Talisman of Ultimate Evil', min: 91, max: 100}
        ]
    },
    Armament: {
        Common: [
            {name: 'Armor of Gleaming', min: 1, max: 10},
            {name: 'Cast-Off Armor', min: 11, max: 20},
            {name: 'Dread Helm', min: 21, max: 30},
            {name: 'Moon-Touched Sword', min: 31, max: 40},
            {name: 'Shield of Expression', min: 41, max: 50},
            {name: 'Silvered Weapon', min: 51, max: 60},
            {name: 'Smoldering Armor', min: 61, max: 70},
            {name: 'Sylvan Talon', min: 71, max: 80},
            {name: 'Veteran’s Cane', min: 81, max: 90},
            {name: 'Walloping Ammunition', min: 91, max: 100}
        ],
        Uncommon: [
            {name: 'Adamantine Armor', min: 1, max: 4},
            {name: 'Adamantine Weapon', min: 5, max: 8},
            {name: 'Ammunition, +1', min: 9, max: 13},
            {name: 'Bracers of Archery', min: 14, max: 18},
            {name: 'Enspelled Armor (cantrip or level 1 spell)', min: 19, max: 23},
            {name: 'Enspelled Weapon (cantrip or level 1 spell)', min: 24, max: 28},
            {name: 'Gauntlets of Ogre Power', min: 29, max: 33},
            {name: 'Javelin of Lightning', min: 34, max: 38},
            {name: 'Mariner’s Armor', min: 39, max: 43},
            {name: 'Mithral Armor', min: 44, max: 48},
            {name: 'Potion of Giant Strength (hill)', min: 49, max: 53},
            {name: 'Potion of Pugilism', min: 54, max: 58},
            {name: 'Quiver of Ehlonna', min: 59, max: 62},
            {name: 'Saddle of the Cavalier', min: 63, max: 66},
            {name: 'Sentinel Shield', min: 67, max: 71},
            {name: 'Shield, +1', min: 72, max: 76},
            {name: 'Sword of Vengeance', min: 77, max: 81},
            {name: 'Trident of Fish Command', min: 82, max: 85},
            {name: 'Weapon, +1', min: 86, max: 90},
            {name: 'Weapon of Warning', min: 91, max: 95},
            {name: 'Wraps of Unarmed Power, +1', min: 96, max: 100}
        ],
        Rare: [
            {name: 'Ammunition, +2', min: 1, max: 3},
            {name: 'Armor, +1', min: 4, max: 7},
            {name: 'Armor of Resistance', min: 8, max: 10},
            {name: 'Armor of Vulnerability', min: 11, max: 13},
            {name: 'Arrow-Catching Shield', min: 14, max: 15},
            {name: 'Belt of Giant Strength (hill)', min: 16, max: 18},
            {name: 'Berserker Axe', min: 19, max: 20},
            {name: 'Daern’s Instant Fortress', min: 21, max: 22},
            {name: 'Dagger of Venom', min: 23, max: 25},
            {name: 'Dragon Slayer', min: 26, max: 28},
            {name: 'Elven Chain', min: 29, max: 31},
            {name: 'Enspelled Armor (level 2 or 3 spell)', min: 32, max: 34},
            {name: 'Enspelled Weapon (level 2 or 3 spell)', min: 35, max: 37},
            {name: 'Flame Tongue', min: 38, max: 40},
            {name: 'Giant Slayer', min: 41, max: 43},
            {name: 'Horn of Blasting', min: 44, max: 46},
            {name: 'Horn of Valhalla (brass or silver)', min: 47, max: 48},
            {name: 'Ioun Stone (protection)', min: 49, max: 51},
            {name: 'Mace of Disruption', min: 52, max: 54},
            {name: 'Mace of Smiting', min: 55, max: 57},
            {name: 'Mace of Terror', min: 58, max: 60},
            {name: 'Potion of Giant Strength (fire)', min: 61, max: 63},
            {name: 'Potion of Giant Strength (frost or stone)', min: 64, max: 66},
            {name: 'Potion of Heroism', min: 67, max: 69},
            {name: 'Potion of Invulnerability', min: 70, max: 72},
            {name: 'Ring of Protection', min: 73, max: 75},
            {name: 'Ring of the Ram', min: 76, max: 78},
            {name: 'Shield, +2', min: 79, max: 81},
            {name: 'Shield of Missile Attraction', min: 82, max: 84},
            {name: 'Sun Blade', min: 85, max: 86},
            {name: 'Sword of Life Stealing', min: 87, max: 88},
            {name: 'Sword of Wounding', min: 89, max: 90},
            {name: 'Tentacle Rod', min: 91, max: 92},
            {name: 'Vicious Weapon', min: 93, max: 94},
            {name: 'Weapon, +2', min: 95, max: 97},
            {name: 'Wraps of Unarmed Power, +2', min: 98, max: 100}
        ],
        'Very Rare': [
            {name: 'Ammunition, +3', min: 1, max: 3},
            {name: 'Ammunition of Slaying', min: 4, max: 6},
            {name: 'Animated Shield', min: 7, max: 9},
            {name: 'Armor, +2', min: 10, max: 12},
            {name: 'Belt of Giant Strength (fire)', min: 13, max: 14},
            {name: 'Belt of Giant Strength (frost or stone)', min: 15, max: 17},
            {name: 'Dancing Sword', min: 18, max: 19},
            {name: 'Demon Armor', min: 20, max: 22},
            {name: 'Dragon Scale Mail', min: 23, max: 25},
            {name: 'Dwarven Plate', min: 26, max: 28},
            {name: 'Dwarven Thrower', min: 29, max: 31},
            {name: 'Energy Bow', min: 32, max: 34},
            {name: 'Enspelled Armor (level 4 or 5 spell)', min: 35, max: 37},
            {name: 'Enspelled Weapon (level 4 or 5 spell)', min: 38, max: 40},
            {name: 'Executioner’s Axe', min: 41, max: 43},
            {name: 'Frost Brand', min: 44, max: 46},
            {name: 'Horn of Valhalla (bronze)', min: 47, max: 49},
            {name: 'Ioun Stone (strength)', min: 50, max: 52},
            {name: 'Lute of Thunderous Thumping', min: 53, max: 55},
            {name: 'Manual of Gainful Exercise', min: 56, max: 58},
            {name: 'Nine Lives Stealer', min: 59, max: 61},
            {name: 'Oathbow', min: 62, max: 64},
            {name: 'Oil of Sharpness', min: 65, max: 68},
            {name: 'Potion of Giant Strength (cloud)', min: 69, max: 72},
            {name: 'Quarterstaff of the Acrobat', min: 73, max: 75},
            {name: 'Scimitar of Speed', min: 76, max: 78},
            {name: 'Shield, +3', min: 79, max: 82},
            {name: 'Shield of the Cavalier', min: 83, max: 85},
            {name: 'Spellguard Shield', min: 86, max: 88},
            {name: 'Sword of Sharpness', min: 89, max: 91},
            {name: 'Thunderous Greatclub', min: 92, max: 94},
            {name: 'Weapon, +3', min: 95, max: 97},
            {name: 'Wraps of Unarmed Power, +3', min: 98, max: 100}
        ],
        Legendary: [
            {name: 'Armor, +3', min: 1, max: 6},
            {name: 'Armor of Invulnerability', min: 7, max: 12},
            {name: 'Belt of Giant Strength (cloud)', min: 13, max: 18},
            {name: 'Belt of Giant Strength (storm)', min: 19, max: 21},
            {name: 'Defender', min: 22, max: 27},
            {name: 'Efreeti Chain', min: 28, max: 33},
            {name: 'Enspelled Armor (level 6, 7, or 8 spell)', min: 34, max: 39},
            {name: 'Enspelled Weapon (level 6, 7, or 8 spell)', min: 40, max: 45},
            {name: 'Hammer of Thunderbolts', min: 46, max: 51},
            {name: 'Holy Avenger', min: 52, max: 56},
            {name: 'Horn of Valhalla (iron)', min: 57, max: 62},
            {name: 'Luck Blade', min: 63, max: 68},
            {name: 'Moonblade', min: 69, max: 72},
            {name: 'Plate Armor of Etherealness', min: 73, max: 78},
            {name: 'Potion of Giant Strength (storm)', min: 79, max: 87},
            {name: 'Rod of Lordly Might', min: 88, max: 90},
            {name: 'Sword of Answering', min: 91, max: 95},
            {name: 'Vorpal Sword', min: 96, max: 100}
        ]
    },
};

function getRandomItem(category, rarity) {
    let items = ITEM_TABLES[category] && ITEM_TABLES[category][rarity];
    if (!items || items.length === 0) return null;
    let idx = Math.floor(Math.random() * items.length);
    let item = items[idx];
    return typeof item === 'string' ? item : item.name;
}

globalThis.ITEM_TABLES = ITEM_TABLES;
globalThis.getRandomItem = getRandomItem;

// --- CR Attribute Reference ---
// (from askthedm_CR_attribute_reference.js)

const CR_ATTRIBUTE_REFERENCE = {
    '0':    { ac: 13, hp: [1, 6], attack: 3, damage: [1, 3], save: 13, xp: 10 },
    '1/8':  { ac: 13, hp: [7, 35], attack: 3, damage: [2, 3], save: 13, xp: 25 },
    '1/4':  { ac: 13, hp: [36, 49], attack: 3, damage: [4, 5], save: 13, xp: 50 },
    '1/2':  { ac: 13, hp: [50, 70], attack: 3, damage: [6, 8], save: 13, xp: 100 },
    '1':    { ac: 13, hp: [71, 85], attack: 3, damage: [9, 14], save: 13, xp: 200 },
    '2':    { ac: 13, hp: [86, 100], attack: 3, damage: [15, 20], save: 13, xp: 450 },
    '3':    { ac: 13, hp: [101, 115], attack: 4, damage: [21, 26], save: 13, xp: 700 },
    '4':    { ac: 14, hp: [116, 130], attack: 5, damage: [27, 32], save: 14, xp: 1100 },
    '5':    { ac: 15, hp: [131, 145], attack: 6, damage: [33, 38], save: 15, xp: 1800 },
    '6':    { ac: 15, hp: [146, 160], attack: 6, damage: [39, 44], save: 15, xp: 2300 },
    '7':    { ac: 15, hp: [161, 175], attack: 6, damage: [45, 50], save: 15, xp: 2900 },
    '8':    { ac: 16, hp: [176, 190], attack: 7, damage: [51, 56], save: 16, xp: 3900 },
    '9':    { ac: 16, hp: [191, 205], attack: 7, damage: [57, 62], save: 16, xp: 5000 },
    '10':   { ac: 17, hp: [206, 220], attack: 7, damage: [63, 68], save: 16, xp: 5900 },
    '11':   { ac: 17, hp: [221, 235], attack: 8, damage: [69, 74], save: 17, xp: 7200 },
    '12':   { ac: 17, hp: [236, 250], attack: 8, damage: [75, 80], save: 17, xp: 8400 },
    '13':   { ac: 18, hp: [251, 265], attack: 8, damage: [81, 86], save: 18, xp: 10000 },
    '14':   { ac: 18, hp: [266, 280], attack: 8, damage: [87, 92], save: 18, xp: 11500 },
    '15':   { ac: 18, hp: [281, 295], attack: 8, damage: [93, 98], save: 18, xp: 13000 },
    '16':   { ac: 18, hp: [296, 310], attack: 9, damage: [99, 104], save: 18, xp: 15000 },
    '17':   { ac: 19, hp: [311, 325], attack: 10, damage: [105, 110], save: 19, xp: 18000 },
    '18':   { ac: 19, hp: [326, 340], attack: 10, damage: [111, 116], save: 19, xp: 20000 },
    '19':   { ac: 19, hp: [341, 355], attack: 10, damage: [117, 122], save: 19, xp: 22000 },
    '20':   { ac: 19, hp: [356, 400], attack: 10, damage: [123, 140], save: 19, xp: 25000 },
    '21':   { ac: 19, hp: [401, 445], attack: 11, damage: [141, 158], save: 20, xp: 33000 },
    '22':   { ac: 19, hp: [446, 490], attack: 11, damage: [159, 176], save: 20, xp: 41000 },
    '23':   { ac: 19, hp: [491, 535], attack: 11, damage: [177, 194], save: 20, xp: 50000 },
    '24':   { ac: 19, hp: [536, 580], attack: 12, damage: [195, 212], save: 21, xp: 62000 },
    '25':   { ac: 19, hp: [581, 625], attack: 12, damage: [213, 230], save: 21, xp: 75000 },
    '26':   { ac: 19, hp: [626, 670], attack: 12, damage: [231, 248], save: 21, xp: 90000 },
    '27':   { ac: 19, hp: [671, 715], attack: 13, damage: [249, 266], save: 22, xp: 105000 },
    '28':   { ac: 19, hp: [716, 760], attack: 13, damage: [267, 284], save: 22, xp: 120000 },
    '29':   { ac: 19, hp: [761, 805], attack: 13, damage: [285, 302], save: 22, xp: 135000 },
    '30':   { ac: 19, hp: [806, 850], attack: 14, damage: [303, 320], save: 23, xp: 155000 }
};
globalThis.CR_ATTRIBUTE_REFERENCE = CR_ATTRIBUTE_REFERENCE;

// --- Damage Type References ---
// (from askthedm_DamageToEffect_reference.js)

const DamageToSave = {
    "bludgeoning": "Strength",
    "thunder": "Strength",
    "force": "Strength",
    "slashing": "Dexterity",
    "fire": "Dexterity",
    "lightning": "Dexterity",
    "acid": "Dexterity",
    "radiant": "Dexterity",
    "piercing": "Constitution",
    "cold": "Constitution",
    "poison": "Constitution",
    "necrotic": "Constitution",
    "psychic": "Wisdom"
};
const DamageToVEffect = {
    "bludgeoning": "blood",
    "piercing": "blood",
    "slashing": "blood",
    "fire": "fire",
    "cold": "frost",
    "lightning": "smoke",
    "acid": "acid",
    "thunder": "frost",
    "poison": "slime",
    "force": "magic",
    "radiant": "holy",
    "necrotic": "death",
    "psychic": "charm"
};
globalThis.DamageToSave = DamageToSave;
globalThis.DamageToVEffect = DamageToVEffect;

// --- Darkvision By Species Reference ---
// (from askthedm_DarkvisionBySpecies_reference.js)

var DarkvisionBySpecies = {
    'aarakocra':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'aasimar':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'autognome':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'bugbear':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'centaur':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'changeling':  {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'deep gnome':  {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'dhampir':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'dragonborn':  {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'duergar':     {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'dwarf':       {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'eladrin':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'elf':         {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'drow':        {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'fairy':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'firbolg':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'genasi':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'giff':        {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'gith':        {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'githyanki':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'githzerai':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'gnome':       {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'goblin':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'goliath':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'hadozee':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'half-elf':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'half-orc':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'halfling':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'harengon':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'hexblood':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'hobgoblin':   {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'human':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kalashtar':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kender':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kenku':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'kobold':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'leonin':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'lizardfolk':  {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'loxodon':     {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'minotaur':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'orc':         {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'owlin':       {night_vision: true, night_vision_distance: 120, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'plasmoid':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'reborn':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'satyr':       {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'sea elf':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'shadar-kai':  {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'shifter':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'simic hybrid':{night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'tabaxi':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'thri-kreen':  {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'tiefling':    {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'tortle':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'triton':      {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'vedalken':    {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'verdan':      {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'warforged':   {night_vision: true, night_vision_distance: 5, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5},
    'yuan-ti':     {night_vision: true, night_vision_distance: 60, night_vision_tint: 'transparent', night_vision_effect: 'dimming', night_vision_effect_range: 5}
    // Add more as needed
};
globalThis.DarkvisionBySpecies = DarkvisionBySpecies;
